version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./secret/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static

  gateway:
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend 
    # volumes:
    #   - static_value:/var/html/static
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
